"""Add Company, Filing, and Analysis models

Revision ID: 4f48d5eb2b27
Revises: b0067a1a039e
Create Date: 2025-07-19 18:01:41.561096

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f48d5eb2b27"
down_revision: str | Sequence[str] | None = "b0067a1a039e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cik", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_companies_cik"), "companies", ["cik"], unique=True)
    op.create_index(op.f("ix_companies_name"), "companies", ["name"], unique=False)
    op.create_table(
        "filings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("accession_number", sa.String(length=20), nullable=False),
        sa.Column("filing_type", sa.String(length=10), nullable=False),
        sa.Column("filing_date", sa.Date(), nullable=False),
        sa.Column("processing_status", sa.String(length=20), nullable=False),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_filings_accession_number"),
        "filings",
        ["accession_number"],
        unique=True,
    )
    op.create_index(
        op.f("ix_filings_company_id"), "filings", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_filings_filing_date"), "filings", ["filing_date"], unique=False
    )
    op.create_index(
        op.f("ix_filings_filing_type"), "filings", ["filing_type"], unique=False
    )
    op.create_index(
        op.f("ix_filings_processing_status"),
        "filings",
        ["processing_status"],
        unique=False,
    )
    op.create_table(
        "analyses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("filing_id", sa.UUID(), nullable=False),
        sa.Column("analysis_type", sa.String(length=50), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.Column("llm_provider", sa.String(length=50), nullable=False),
        sa.Column("llm_model", sa.String(length=100), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["filing_id"], ["filings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analyses_analysis_type"), "analyses", ["analysis_type"], unique=False
    )
    op.create_index(
        op.f("ix_analyses_confidence_score"),
        "analyses",
        ["confidence_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analyses_created_at"), "analyses", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_analyses_created_by"), "analyses", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_analyses_filing_id"), "analyses", ["filing_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analyses_filing_id"), table_name="analyses")
    op.drop_index(op.f("ix_analyses_created_by"), table_name="analyses")
    op.drop_index(op.f("ix_analyses_created_at"), table_name="analyses")
    op.drop_index(op.f("ix_analyses_confidence_score"), table_name="analyses")
    op.drop_index(op.f("ix_analyses_analysis_type"), table_name="analyses")
    op.drop_table("analyses")
    op.drop_index(op.f("ix_filings_processing_status"), table_name="filings")
    op.drop_index(op.f("ix_filings_filing_type"), table_name="filings")
    op.drop_index(op.f("ix_filings_filing_date"), table_name="filings")
    op.drop_index(op.f("ix_filings_company_id"), table_name="filings")
    op.drop_index(op.f("ix_filings_accession_number"), table_name="filings")
    op.drop_table("filings")
    op.drop_index(op.f("ix_companies_name"), table_name="companies")
    op.drop_index(op.f("ix_companies_cik"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
